### PR TITLE
General Improvements

### PR DESCRIPTION
**Pull request by ripsnortntear**
This was quick and dirty. please look over changes to see if you want them..

Changes made:

Simplified the conditionals: Instead of using ! -z, I used -n to check for a non-empty string.

Removed unnecessary nesting: The inner if statements were not necessary, and the logic can be simplified by using a single conditional branch.

Removed redundant echo " " statements: The extra newline characters were not necessary.

Combined the two if statements: The logic can be simplified by using an elif statement to handle the case where BACKUPS is not false and BACKUP_INTERVAL is set.

### CODE REVIEW

**Comment by luxusburg** [comment]
Hi, thanks for the changes I will go threw everything tomorrow sadly was quite busy these days! Thanks for improving the code base

**Comment by luxusburg** [comment]
Hello,
I tested your change looks all good but there is a problem with the env2cfg.sh changes:

1. We need to change all the uppercase env to lower that's easily done by simply adding `${var,,}` 
2. Next problem is some environment names are not the same as the ones used by the server for example `SERVER_PWD` != `server_password` 
How do you want to handle the second problem?

**Comment by ripsnortntear** [comment]
actually after careful research and review.. you had it right the first time. it will have to process each one.
env2cfg.sh can be left alone.

**Review by ripsnortntear — COMMENTED** [review]
You could align the Docker environment variables with the entries in app.cfg, which might remove the necessity to modify the variables.

**Comment by luxusburg** [comment]
Sure that's also what i thought, but I think changing the environment varibales is not good for the current users.
I probably prefer to add only if conditions for the environment variables that don't fit

**Comment by ripsnortntear** [comment]
That sounds like a plan. I really like this Docker image.

**Comment by luxusburg** [comment]
Sorry for my late follow-up I will look through this tomorrow and do the merge was quite busy the last days and had no energy for the follow-up. I am sorry

**Pull request merged**
