### PR TITLE
added: possible fix for x11 error on restart

### PR DESCRIPTION
**Pull request by Requion**
This is an attempt to fix the "X server is already running" error which sometimes comes up after restart. I am not completely sure as to why this happens, but this fix shouldn't do any harm because we want to start on a "clean state" anyway.

### CODE REVIEW

**Comment by luxusburg** [comment]
Hi @Requion I will pull it tomorrow! Sounds like a reasonable fix to apply

Thanks for the help 🙏

**Comment by luxusburg** [comment]
Okay no problem I will wait for your feedback 😊

**Comment by Requion** [comment]
So, i updated the PR. The suspicion i had yesterday was that this error might come up because a docker restart only `SIGTERM`s the main process. Because the X Server (`Xvfb`) is run as a background task, it might not be guaranteed that it will be stopped gracefully.

All in all i hope that this is a cleaner fix. We might still add the cleanup of `/tmp` at the start of the script but lets first test if this works.

**Comment by Requion** [comment]
Okay, so i did some testing and it didn't work as expected, which i kinda expected actually. The issue is that if the `kill` line isn't executed for whatever reason, the issue still appears.

I added the earlier removal of the `.X0-lock` file again

**Comment by luxusburg** [comment]
Thanks for testing! I learned something new from you!
Can I start the merge and update the image of the changes?
Do we need another cleanup of `/tmp` like a complete rm `-r /tmp` or is that too much?

**Comment by Requion** [comment]
I am still testing the latest change but it looks promising. So you can merge at your discretion.

I also thought about just nuking `/tmp`. It shouldn't cause issues because a) everything in there should be gone anyway and b) there shouldn't be anything we _need_ to persist.

**Comment by luxusburg** [comment]
I will wait for your last testing before I merge

**Pull request merged**
